# Generated by Django 4.2.7 on 2023-11-25 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('disease_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Болезнь',
                'verbose_name_plural': 'Болезни',
                'db_table': 'diseases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('medication_id', models.AutoField(primary_key=True, serialize=False)),
                ('medication_name', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('medication_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Лекарство',
                'verbose_name_plural': 'Лекарства',
                'db_table': 'medications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('symptom_id', models.AutoField(primary_key=True, serialize=False)),
                ('symptom_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Симптом',
                'verbose_name_plural': 'Симптомы',
                'db_table': 'symptoms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiseaseSymptomLink',
            fields=[
                ('disease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                                 serialize=False, to='main.diseases')),
            ],
            options={
                'verbose_name': 'Связь болезни и симптома',
                'verbose_name_plural': 'Связи болезней и симптомов',
                'db_table': 'disease_symptom_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicationDiseaseLink',
            fields=[
                ('medication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                                    serialize=False, to='main.medications')),
            ],
            options={
                'verbose_name': 'Связь лекарства и болезни',
                'verbose_name_plural': 'Связь лекарства и болезней',
                'db_table': 'medication_disease_link',
                'managed': False,
            },
        ),
    ]
